pelican:
  notify:         site-cvs@apache.org
  autobuild:      true
  target:         asf-site
  
staging:
  whoami: asf-site

github:
  description: ASF Foundation Website
  homepage:    https://www.apache.org/
  labels:
    - website
    - pelican

notifications:
  commits:      site-cvs@apache.org
  issues:       centralservices@apache.org
  pullrequests: centralservices@apache.org

